export const owners = [
  {
    id: 1,
    fullName: 'Savannah Nguyen',
    endDate: '1/15/12',
    profits: '$328.85',
    losses: '$779.58',
    phone: '(983) 555-0123',
  },
  {
    id: 2,
    fullName: 'Jenny Wilson',
    endDate: '8/30/14',
    profits: '$948.55',
    losses: '$589.99',
    phone: '(980) 555-0129',
  },
  {
    id: 3,
    fullName: 'Annette Black',
    endDate: '5/30/14',
    profits: '$778.35',
    losses: '$948.55',
    phone: '(978) 555-0121',
  },
  {
    id: 4,
    fullName: 'Kathryn Murphy',
    endDate: '11/7/16',
    profits: '$169.43',
    losses: '$202.87',
    phone: '(912) 555-0107',
  },
  {
    id: 5,
    fullName: 'Cameron Williamson',
    endDate: '7/27/13',
    profits: '$782.01',
    losses: '$710.68',
    phone: '(903) 555-0105',
  },
  {
    id: 6,
    fullName: 'Kristin Watson',
    endDate: '5/19/12',
    profits: '$767.50',
    losses: '$779.58',
    phone: '(925) 555-0118',
  },
  {
    id: 7,
    fullName: 'Eleanor Pena',
    endDate: '8/21/15',
    profits: '$475.22',
    losses: '$219.78',
    phone: '(205) 555-0100',
  },
  {
    id: 8,
    fullName: 'Guy Hawkins',
    endDate: '5/27/15',
    profits: '$576.28',
    losses: '$446.61',
    phone: '(907) 555-0119',
  },
  {
    id: 9,
    fullName: 'Brooklyn Simmons',
    endDate: '3/4/16',
    profits: '$219.78',
    losses: '$928.41',
    phone: '(901) 555-0124',
  },
  {
    id: 10,
    fullName: 'Robert Fox',
    endDate: '4/4/18',
    profits: '$202.87',
    losses: '$275.43',
    phone: '(984) 555-0102',
  },
  {
    id: 11,
    fullName: 'Noah Connolly',
    endDate: '5/11/22',
    profits: '$252.00',
    losses: '$12.17',
    phone: '(964) 545-0942',
  },
  {
    id: 12,
    fullName: 'Lucy Farrell',
    endDate: '5/10/21',
    profits: '$1002.30',
    losses: '$28.50',
    phone: '(914) 945-0972',
  },
  {
    id: 13,
    fullName: 'Emma Fitzgerald',
    endDate: '5/11/22',
    profits: '$902.30',
    losses: '$22.70',
    phone: '(994) 145-7822',
  },
  {
    id: 14,
    fullName: 'Conor Healy',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 15,
    fullName: 'Lily Dunne',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 16,
    fullName: 'Cillian Clarke',
    endDate: '1/9/21',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 17,
    fullName: 'Olivia Carroll',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 18,
    fullName: 'Jamie Gallagher',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 19,
    fullName: 'Chloe Murphy',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 20,
    fullName: 'Darragh Daly',
    endDate: '7/6/23',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 21,
    fullName: 'Aoife Connell',
    endDate: '5/10/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 22,
    fullName: 'Caoimhe Flynn',
    endDate: '5/11/21',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 23,
    fullName: 'Luke Collins',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 24,
    fullName: 'Molly Kennedy',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 25,
    fullName: 'Charlie Connor',
    endDate: '5/11/21',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 26,
    fullName: 'Harry Johnston',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 27,
    fullName: 'Oisín Callaghan',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 28,
    fullName: 'Anna Byrne',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 29,
    fullName: 'James Mahony',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 30,
    fullName: 'Daniel Maguire',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 31,
    fullName: 'Sophia Hughes',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  // {
  //   id: 32,
  //   fullName: 'Patrick MacCarthy',
  //   endDate: '5/11/22',
  //   profits: '',
  //   losses: '',
  //   phone: null,
  // },
  // {
  //   id: 33,
  //   fullName: 'Adam Campbell',
  //   endDate: '5/11/22',
  //   profits: '',
  //   losses: '',
  //   phone: null,
  // },
  // {
  //   id: 34,
  //   fullName: 'Michael Murray',
  //   endDate: '5/11/22',
  //   profits: '',
  //   losses: '',
  //   phone: null,
  // },
  // {
  //   id: 35,
  //   fullName: 'Freya Boyle',
  //   endDate: '5/11/22',
  //   profits: '',
  //   losses: '',
  //   phone: null,
  // },
  // {
  //   id: 36,
  //   fullName: 'Alex Lynch',
  //   endDate: '5/11/22',
  //   profits: '',
  //   losses: '',
  //   phone: null,
  // },
  // {
  //   id: 37,
  //   fullName: 'Fionn Thompson',
  //   endDate: '16/01/24',
  //   profits: '',
  //   losses: '',
  //   phone: null,
  // },
  // {
  //   id: 38,
  //   fullName: 'Saoirse Walsh',
  //   endDate: '5/11/22',
  //   profits: '',
  //   losses: '',
  //   phone: null,
  // },
  // {
  //   id: 39,
  //   fullName: 'Liam Reilly',
  //   endDate: '5/11/22',
  //   profits: '',
  //   losses: '',
  //   phone: null,
  // },
  // {
  //   id: 40,
  //   fullName: 'Tadhg Duffy',
  //   endDate: '2/12/23',
  //   profits: '',
  //   losses: '',
  //   phone: null,
  // },
  // {
  //   id: 41,
  //   fullName: 'Kate Brown',
  //   endDate: '5/11/22',
  //   profits: '',
  //   losses: '',
  //   phone: null,
  // },
  // {
  //   id: 42,
  //   fullName: 'Jack Brennan',
  //   endDate: '5/11/22',
  //   profits: '',
  //   losses: '',
  //   phone: null,
  // },
]
