export const data = [
  {
    id: 1,
    name: 'Noah Connolly',
    endDate: '5/11/22',
    profits: '2323',
    losses: '',
    phone: null,
  },
  {
    id: 2,
    name: 'Lucy Farrell',
    endDate: '5/10/21',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 3,
    name: 'Emma Fitzgerald',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 4,
    name: 'Conor Healy',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 5,
    name: 'Lily Dunne',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 6,
    name: 'Cillian Clarke',
    endDate: '1/9/21',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 7,
    name: 'Olivia Carroll',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 9,
    name: 'Jamie Gallagher',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 10,
    name: 'Chloe Murphy',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 11,
    name: 'Darragh Daly',
    endDate: '7/6/23',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 12,
    name: 'Aoife Connell',
    endDate: '5/10/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 13,
    name: 'Caoimhe Flynn',
    endDate: '5/11/21',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 14,
    name: 'Luke Collins',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 15,
    name: 'Molly Kennedy',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 16,
    name: 'Charlie Connor',
    endDate: '5/11/21',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 17,
    name: 'Harry Johnston',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 18,
    name: 'Oisín Callaghan',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 19,
    name: 'Anna Byrne',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 20,
    name: 'James Mahony',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 21,
    name: 'Daniel Maguire',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 22,
    name: 'Sophia Hughes',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 23,
    name: 'Patrick MacCarthy',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 24,
    name: 'Adam Campbell',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 25,
    name: 'Michael Murray',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 26,
    name: 'Freya Boyle',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 27,
    name: 'Alex Lynch',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 28,
    name: 'Fionn Thompson',
    endDate: '16/01/24',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 29,
    name: 'Saoirse Walsh',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 30,
    name: 'Liam Reilly',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 31,
    name: 'Tadhg Duffy',
    endDate: '2/12/23',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 32,
    name: 'Kate Brown',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
  {
    id: 33,
    name: 'Jack Brennan',
    endDate: '5/11/22',
    profits: '',
    losses: '',
    phone: null,
  },
]
